// Generated by gencpp from file mqtt_client/IsConnected.msg
// DO NOT EDIT!


#ifndef MQTT_CLIENT_MESSAGE_ISCONNECTED_H
#define MQTT_CLIENT_MESSAGE_ISCONNECTED_H

#include <ros/service_traits.h>


#include <mqtt_client/IsConnectedRequest.h>
#include <mqtt_client/IsConnectedResponse.h>


namespace mqtt_client
{

struct IsConnected
{

typedef IsConnectedRequest Request;
typedef IsConnectedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsConnected
} // namespace mqtt_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mqtt_client::IsConnected > {
  static const char* value()
  {
    return "e0cdaf65159c7f3563426650fb8d3f64";
  }

  static const char* value(const ::mqtt_client::IsConnected&) { return value(); }
};

template<>
struct DataType< ::mqtt_client::IsConnected > {
  static const char* value()
  {
    return "mqtt_client/IsConnected";
  }

  static const char* value(const ::mqtt_client::IsConnected&) { return value(); }
};


// service_traits::MD5Sum< ::mqtt_client::IsConnectedRequest> should match
// service_traits::MD5Sum< ::mqtt_client::IsConnected >
template<>
struct MD5Sum< ::mqtt_client::IsConnectedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mqtt_client::IsConnected >::value();
  }
  static const char* value(const ::mqtt_client::IsConnectedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mqtt_client::IsConnectedRequest> should match
// service_traits::DataType< ::mqtt_client::IsConnected >
template<>
struct DataType< ::mqtt_client::IsConnectedRequest>
{
  static const char* value()
  {
    return DataType< ::mqtt_client::IsConnected >::value();
  }
  static const char* value(const ::mqtt_client::IsConnectedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mqtt_client::IsConnectedResponse> should match
// service_traits::MD5Sum< ::mqtt_client::IsConnected >
template<>
struct MD5Sum< ::mqtt_client::IsConnectedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mqtt_client::IsConnected >::value();
  }
  static const char* value(const ::mqtt_client::IsConnectedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mqtt_client::IsConnectedResponse> should match
// service_traits::DataType< ::mqtt_client::IsConnected >
template<>
struct DataType< ::mqtt_client::IsConnectedResponse>
{
  static const char* value()
  {
    return DataType< ::mqtt_client::IsConnected >::value();
  }
  static const char* value(const ::mqtt_client::IsConnectedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MQTT_CLIENT_MESSAGE_ISCONNECTED_H
