// Generated by gencpp from file mqtt_client/IsConnectedRequest.msg
// DO NOT EDIT!


#ifndef MQTT_CLIENT_MESSAGE_ISCONNECTEDREQUEST_H
#define MQTT_CLIENT_MESSAGE_ISCONNECTEDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mqtt_client
{
template <class ContainerAllocator>
struct IsConnectedRequest_
{
  typedef IsConnectedRequest_<ContainerAllocator> Type;

  IsConnectedRequest_()
    {
    }
  IsConnectedRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IsConnectedRequest_

typedef ::mqtt_client::IsConnectedRequest_<std::allocator<void> > IsConnectedRequest;

typedef boost::shared_ptr< ::mqtt_client::IsConnectedRequest > IsConnectedRequestPtr;
typedef boost::shared_ptr< ::mqtt_client::IsConnectedRequest const> IsConnectedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mqtt_client::IsConnectedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace mqtt_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::mqtt_client::IsConnectedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mqtt_client/IsConnectedRequest";
  }

  static const char* value(const ::mqtt_client::IsConnectedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::mqtt_client::IsConnectedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IsConnectedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mqtt_client::IsConnectedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mqtt_client::IsConnectedRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MQTT_CLIENT_MESSAGE_ISCONNECTEDREQUEST_H
